import pygame

class Player:
    
    def __init__(self, boardGame, coin):
        pass

    def putCoin(self, screen, index, col):
        """
            Returns True if column is full else, put the coin and returns False.
            :param "screen": screen generated by pygame. 
            :param "index": either player 1 or player 2
            :param "col": poisition of the coin.
        """
        pass


